# ===================================================================
# Spring Boot configuration for the "secret-samples" profile.
#
# This configuration overrides the application.yml file.
#
# More information on profiles: https://www.jhipster.tech/profiles/
# More information on configuration properties: https://www.jhipster.tech/common-application-properties/
# ===================================================================

# ===================================================================
# Samples for required secrets to be used in development and ci using prod profile.
# ===================================================================

spring:
  datasource:
    username: inventoryCapstone
    password:

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: YWRjYmNjZjhhYjlmZjJkZWJmZjAzZGZjMDI0YmY0OWYyNmVlZjk2YTdlNTUyMzdjYWY0ZjU1NDczYmNlNzE1YzE4ODEwOWYxMTQzNTU2MDEzMWRmY2I4YTZhZDhkOGZmYmIwM2IzMjhlM2IzOWJiOTZkYzgwMGYyNjZjMjI3ZDY=
